//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordPressReader.Phone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordPressReader.Phone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your username and email before you can comment on an article, tap OK below if you want to set them now..
        /// </summary>
        public static string Account_NoCredentials_Message {
            get {
                return ResourceManager.GetString("Account_NoCredentials_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Credentials.
        /// </summary>
        public static string Account_NoCredentials_Title {
            get {
                return ResourceManager.GetString("Account_NoCredentials_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear data.
        /// </summary>
        public static string Account_Settings_ClearData {
            get {
                return ResourceManager.GetString("Account_Settings_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Settings_Email {
            get {
                return ResourceManager.GetString("Account_Settings_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To comment on articles you must have your user name and email address set..
        /// </summary>
        public static string Account_Settings_Text {
            get {
                return ResourceManager.GetString("Account_Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account_Settings_Title {
            get {
                return ResourceManager.GetString("Account_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Account_Settings_UserName {
            get {
                return ResourceManager.GetString("Account_Settings_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string AppBarButtonComments {
            get {
                return ResourceManager.GetString("AppBarButtonComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reload.
        /// </summary>
        public static string AppBarButtonReload {
            get {
                return ResourceManager.GetString("AppBarButtonReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarButtonSettings {
            get {
                return ResourceManager.GetString("AppBarButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string AppBarButtonShare {
            get {
                return ResourceManager.GetString("AppBarButtonShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        public static string CreatedAt_a_minute_ago {
            get {
                return ResourceManager.GetString("CreatedAt_a_minute_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        public static string CreatedAt_days_ago {
            get {
                return ResourceManager.GetString("CreatedAt_days_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string CreatedAt_hours_ago {
            get {
                return ResourceManager.GetString("CreatedAt_hours_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a moment ago.
        /// </summary>
        public static string CreatedAt_Just_a_moment_ago {
            get {
                return ResourceManager.GetString("CreatedAt_Just_a_moment_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        public static string CreatedAt_minutes_ago {
            get {
                return ResourceManager.GetString("CreatedAt_minutes_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds ago.
        /// </summary>
        public static string CreatedAt_seconds_ago {
            get {
                return ResourceManager.GetString("CreatedAt_seconds_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a day ago.
        /// </summary>
        public static string CreatedAt_yesterday {
            get {
                return ResourceManager.GetString("CreatedAt_yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reach server.\nPlease try again later..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string Lead_Comments {
            get {
                return ResourceManager.GetString("Lead_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait.
        /// </summary>
        public static string ProgressControlPleaseWait {
            get {
                return ResourceManager.GetString("ProgressControlPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading….
        /// </summary>
        public static string ProgressControlReloading {
            get {
                return ResourceManager.GetString("ProgressControlReloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
